---
title: Millfields Coffee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.millfields.co
description: Neighborhood café serving up coffee, tea and mad good brunch. Kid, dog and vegan friendly!
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Millfields
email: hello@onlyjerkin.com
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  instagram: https://www.instagram.com/millfieldscoffee/
  facebook: https://www.facebook.com/millfieldscoffee/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: millfields.imgix.net
menu-file: "/uploads/millfields-menu.pdf"